### ISSUE TITLE
Name of package should be prefixed by biosimulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/Biosimulations_SimulatorDockerImageTemplate#2]
In the setup template, the name of the pip package is set to "my_simulator". This would conflict with the simulator itself if installed on the same virtual env. Should this be changed to "biosimulations_my_simulator" to make clear that this is the setup file for the wrapper?

**Comment by jonrkarr** [comment]
Clarifying this is good. I was just using `my_simulator` as a placeholder.

**Comment by bilalshaikh42** [comment]
To clarify, I think the confusion for me is if the template is intended to be a wrapper for simulators whose code is stored elsewhere or if the simulator package would be included in the repository. I would prefer the first approach as it would help us avoid some of the issues in #1 and also help with keeping the images tagged for each version.
We can add some more comments specifying when to point to the docker repository/image/licence and when to point to the original package repo/licence.
